### ISSUE TITLE
Documentation on Dual boot process and validating them:

### ISSUE THREAD

**Issue by Anilkumar18** [SociOS-Linux/socios#14]
- [ ] Documenting the steps used for creating scripts and adding steps for deploying them on the mac machine. 
- [ ] Validate the dual booting process on the Mac machine.

**Comment by mdheller** [comment]
I feel like we are shuffling cards around. This one is connected to other issues including the below:
[Documentation for booting the ISO:](https://github.com/SociOS-Linux/socios/issues/10)
[Documentation for script and implementation:](https://github.com/SociOS-Linux/socios/issues/7)

For this reason I am making this one as a duplicate.
